### ISSUE TITLE
Bug: Some subtitles may not be fully displayed

### ISSUE THREAD

**Issue by dyphire** [christoph-heinrich/mpv-subtitle-lines#2]
Sample subtitles: [sample-subs.zip](https://github.com/christoph-heinrich/mpv-subtitle-lines/files/13547772/sample-subs.zip)

Load sample subtitles during mpv playback and browse the subtitle content through this script. Unable to display subtitle content after 0:36:46.

**Comment by christoph-heinrich** [comment]
The problem here is that at that time there is a dialogue line and a moving sign at the same time. Each time the sign position update is considered a new line, but since they overlap in time I get the exact same values each time for `sub-text`, `sub-start` and `sub-end`.

Increasing the retries to at least 45 makes it work, but that seems like a terrible solution. I'll have to think of something better. maybe checking if the sub-delay changed and going off of that?

I'll do some testing and you can increase the retry count as a temporary workaround.

**Comment by christoph-heinrich** [comment]
Would you mind testing that PR?
I'll be using that for at least a week myself and if we don't encounter any problems until then I'll merge it.

**Comment by dyphire** [comment]
> Would you mind testing that PR? I'll be using that for at least a week myself and if we don't encounter any problems until then I'll merge it.

It works. But at the end of the menu, a large amount of repetitive subtitle content will still be displayed. Is it possible to further optimize it?

**Comment by christoph-heinrich** [comment]
60% of subtitle file is for the same subtitle line. wtf...

That's because it's moving, and it's rendered in a lot of small slices to get that gradient effect (each slice with a slightly different color).

So what we get from mpv for that section looks like this, a ton of times with varying start and end times.
![image](https://github.com/christoph-heinrich/mpv-subtitle-lines/assets/8932183/f2bd2c9d-b033-40ba-ae34-37b8cce1316d)

Because that text gets displayed that many times at the same time, it also shows up that often in the list.

I've added a commit to also merge identical lines that are shown at the same time. With that it will also merge lines when two characters say the same thing at the same time, but I guess that's not that much of a problem.

**Comment by dyphire** [comment]
The following patches are needed to fix the crash caused by opening menus when idle.
```diff
---
 subtitle-lines.lua | 1 +
 1 file changed, 1 insertion(+)

diff --git a/subtitle-lines.lua b/subtitle-lines.lua
index 189cfd5..030ac6a 100644
--- a/subtitle-lines.lua
+++ b/subtitle-lines.lua
@@ -167,6 +167,7 @@ local function show_subtitle_list(subtitles)
     local last_started_index = 0
     local last_active_index = nil
     local time = mp.get_property_number('time-pos', 0) + SUB_SEEK_OFFSET
+    if not subtitles then return end
     for i, subtitle in ipairs(subtitles) do
         local has_started = subtitle.start <= time
         local has_ended = subtitle.stop < time
-- 
```

**Comment by christoph-heinrich** [comment]
I don't see how opening the menu while idle can cause a crash, but having the menu open when a file ends and the player goes to idle might be problematic.

It doesn't make sense to keep the menu open across file boundaries (open, closing and switching files), so we could close it. Does this work for you?

```diff
diff --git a/subtitle-lines.lua b/subtitle-lines.lua
index f207f61..622b97b 100644
--- a/subtitle-lines.lua
+++ b/subtitle-lines.lua
@@ -227,6 +227,10 @@ mp.register_script_message('uosc-menu-closed', function()
     mp.unobserve_property(sub_text_update)
 end)
 
+mp.register_event('start-file', function()
+    mp.commandv('script-message-to', 'uosc', 'close-menu', 'subtitle-lines-list')
+end)
+
 mp.register_event('end-file', function()
-    subtitles = nil
+    mp.commandv('script-message-to', 'uosc', 'close-menu', 'subtitle-lines-list')
 end)
```

**Comment by dyphire** [comment]
Your patch cannot fix the crash issue caused by accidentally opening menus at idle, it is just an improvement to the current situation rather than a fix. Of course, this patch is equally meaningful.

**Comment by christoph-heinrich** [comment]
> crash issue caused by accidentally opening menus at idle

When I open the menu while idle I get an empty menu.

[this](https://github.com/christoph-heinrich/mpv-subtitle-lines/blob/e8f3e5e18742708ab777dfb0bfb536f5d9f8dd34/subtitle-lines.lua#L220) gets subtitles from [this](https://github.com/christoph-heinrich/mpv-subtitle-lines/blob/e8f3e5e18742708ab777dfb0bfb536f5d9f8dd34/subtitle-lines.lua#L138), which is initialized [here](https://github.com/christoph-heinrich/mpv-subtitle-lines/blob/e8f3e5e18742708ab777dfb0bfb536f5d9f8dd34/subtitle-lines.lua#L100) and there are no early returns, so I don't see how it could possibly be `nil`.

**Comment by dyphire** [comment]
> > crash issue caused by accidentally opening menus at idle
> 
> When I open the menu while idle I get an empty menu.
> 
> [this](https://github.com/christoph-heinrich/mpv-subtitle-lines/blob/e8f3e5e18742708ab777dfb0bfb536f5d9f8dd34/subtitle-lines.lua#L220) gets subtitles from [this](https://github.com/christoph-heinrich/mpv-subtitle-lines/blob/e8f3e5e18742708ab777dfb0bfb536f5d9f8dd34/subtitle-lines.lua#L138), which is initialized [here](https://github.com/christoph-heinrich/mpv-subtitle-lines/blob/e8f3e5e18742708ab777dfb0bfb536f5d9f8dd34/subtitle-lines.lua#L100) and there are no early returns, so I don't see how it could possibly be `nil`.

I also can no longer reproduce the crash, only encountered it in previous tests.
